### ISSUE TITLE
Installing without cloning repo

### ISSUE THREAD

**Issue by xhluca** [McGill-NLP/polytropon#1]
It would be nice if this package could be installed through https://pypi.org/ or via git, i.e.:

```
pip install polytropon # pypi
pip install git+https://github.com/McGill-NLP/polytropon  # git
```

I tried doing the latter (as it usually works) but it doesn't currently work. It might be related to how `setup.py` detects the `src/` folder.

**Comment by xhluca** [comment]
Ok I investigated this in https://github.com/xhlulu/simple-pip-example

Setuptools docs were pretty terse about the subject. From what i understand it must be a module (i.e. a folder with a `__init__.py` file), which means the code in `src/polytropon.py` needs to be moved to`src/polytropon/__init__.py`. I can do a PR if needed

**Comment by ducdauge** [comment]
Hey Xing Han, many thanks for the tip! I made the necessary changes to allow for installation via pip+git. It seems to work for me, could you please verify?

**Comment by xhluca** [comment]
Thanks! Now the installs works but it runs into this error when you try to import:

```
>>> from polytropon.polytropon import SkilledMixin
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
   from adapters import (
ModuleNotFoundError: No module named 'adapters'
```

I added a fix in this: https://github.com/McGill-NLP/polytropon/pull/3
