### ISSUE TITLE
Code for training the model

### ISSUE THREAD

**Issue by phquang** [McGill-NLP/polytropon#7]
Hi @ducdauge,

Thanks for publishing the implementation!
I wonder if you could share with me the code to train the models on the BabyAI and CrossFit benchmarks? My email address is hqpham.2017@phdcs.smu.edu.sg

Thanks

**Comment by fwangut** [comment]
Hi @ducdauge 

I also would like to request a copy of the code for the CrossFit experiments. Could you please share the code? My email address is fwang.ut@gmail.com

Thanks!

**Comment by ducdauge** [comment]
Thanks for your enquiry, I sent you both the repos.

**Comment by BaohaoLiao** [comment]
Hi @ducdauge, is it also possible for you to send me the code? Or release your code? My email is b.liao@uva.nl. Thank you in advance

**Comment by ducdauge** [comment]
Hi @BaohaoLiao I am working on a new version of the repo together with the co-authors from Microsoft. Stay tuned, it will be released shortly :)
